resources:
    - name: src
      type: git
      source:
        uri: git@github.com:simonkey007/demo_project.git
        branch: master
        private_key: ((github-private-key))

jobs:
    - name: test credentials
      plan:
      - get: src
      - task: echo
        vars:
            szymon: "blabla"
        file: src/task.yml
    