resources:
    - name: demo_project
      type: git
      source:
        uri: git@github.com:simonkey007/demo_project.git
        branch: master
        private_key: ((github-private-key))

groups:
  - name: test-account
    jobs:
      - Deploy TEST eu-central-1
      - Deploy TEST us-east-1
  
  - name: stage-account
    jobs:
      - Deploy STAGE eu-central-1
      - Deploy STAGE us-east-1

  - name: destroy
    jobs:
      - Destroy TEST eu-central-1
      - Destroy TEST us-east-1
      - Destroy STAGE eu-central-1
      - Destroy STAGE us-east-1

jobs:
    - name: Deploy TEST eu-central-1
      plan:
      - get: demo_project
        trigger: true
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: create-s3-bucket
        vars:
          env: "test"
          region: "eu-central-1"
        file: demo_project/task2.yml

    - name: Deploy TEST us-east-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: create-s3-bucket
        vars:
          env: "test"
          region: "us-east-1"
        file: demo_project/task2.yml

    - name: Destroy TEST eu-central-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: destroy-s3-bucket
        vars:
          env: "test"
          region: "eu-central-1"
        file: demo_project/task3.yml

    - name: Destroy TEST us-east-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: destroy-s3-bucket
        vars:
          env: "test"
          region: "us-east-1"
        file: demo_project/task3.yml

    - name: Deploy STAGE eu-central-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: create-s3-bucket
        vars:
          env: "stage"
          region: "eu-central-1"
        file: demo_project/task2.yml

    - name: Deploy STAGE us-east-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: create-s3-bucket
        vars:
          env: "stage"
          region: "us-east-1"
        file: demo_project/task2.yml

    - name: Destroy STAGE eu-central-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: destroy-s3-bucket
        vars:
          env: "stage"
          region: "eu-central-1"
        file: demo_project/task3.yml

    - name: Destroy STAGE us-east-1
      plan:
      - get: demo_project
      - task: get-secret-from-vault
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: destroy-s3-bucket
        vars:
          env: "stage"
          region: "us-east-1"
        file: demo_project/task3.yml