resources:
    - name: demo_project
      type: git
      source:
        uri: git@github.com:simonkey007/demo_project.git
        branch: master
        private_key: ((github-private-key))

jobs:
    - name: test credentials
      plan:
      - get: demo_project
        trigger: true
      - task: echo
        vars:
            szymon: ((test))
        file: demo_project/task.yml
      - task: sts
        file: demo_project/task2.yml
    